name: spain

env:
  countrycode: ES

on:
  workflow_dispatch:
  workflow_run:
    workflows: [start map builds]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maps:
          [
            {name: andalucia, url: https://download.geofabrik.de/europe/spain/andalucia-latest.osm.pbf, state: "0100"},
            {name: aragon, url: https://download.geofabrik.de/europe/spain/aragon-latest.osm.pbf, state: "0200"},
            {name: asturias, url: https://download.geofabrik.de/europe/spain/asturias-latest.osm.pbf, state: "0300"},
            {name: cantabria, url: https://download.geofabrik.de/europe/spain/cantabria-latest.osm.pbf, state: "0400"},
            {name: castilla-la-mancha, url: https://download.geofabrik.de/europe/spain/castilla-la-mancha-latest.osm.pbf, state: "0500"},
            {name: castilla-y-leon, url: https://download.geofabrik.de/europe/spain/castilla-y-leon-latest.osm.pbf, state: "0600"},
            {name: cataluna, url: https://download.geofabrik.de/europe/spain/cataluna-latest.osm.pbf, state: "0700"},
            {name: ceuta, url: https://download.geofabrik.de/europe/spain/ceuta-latest.osm.pbf, state: "0800"},
            {name: extremadura, url: https://download.geofabrik.de/europe/spain/extremadura-latest.osm.pbf, state: "0900"},
            {name: galicia, url: https://download.geofabrik.de/europe/spain/galicia-latest.osm.pbf, state: "1000"},
            {name: islas-baleares, url: https://download.geofabrik.de/europe/spain/islas-baleares-latest.osm.pbf, state: "1100"},
            {name: la-rioja, url: https://download.geofabrik.de/europe/spain/la-rioja-latest.osm.pbf, state: "1200"},
            {name: madrid, url: https://download.geofabrik.de/europe/spain/madrid-latest.osm.pbf, state: "1300"},
            {name: melilla, url: https://download.geofabrik.de/europe/spain/melilla-latest.osm.pbf, state: "1400"},
            {name: murcia, url: https://download.geofabrik.de/europe/spain/murcia-latest.osm.pbf, state: "1500"},
            {name: navarra, url: https://download.geofabrik.de/europe/spain/navarra-latest.osm.pbf, state: "1600"},
            {name: pais-vasco, url: https://download.geofabrik.de/europe/spain/pais-vasco-latest.osm.pbf, state: "1700"},
            {name: valencia, url: https://download.geofabrik.de/europe/spain/valencia-latest.osm.pbf, state: "1800"},
          ]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup Env
        run: |
          sudo apt-get update 
          sudo apt-get install wget openjdk-21-jre python3 pip
          pip install numpy
          echo "freeing ~10gb of disk space"
          sudo rm -rf /usr/local/lib/android || true

      - name: omsis-cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: osmosis
          key: osmsis-cache

      - name: omsis
        if: steps.cache.outputs.cache-hit != 'true'
        run: sh setup_env.sh

      - name: Build
        run: |
          /usr/bin/time -v python generate_map.py -i ${{ matrix.maps.url }} -c $countrycode -s ${{ matrix.maps.state }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-${{ matrix.maps.name }}
          path: ./*.map

