name: united-kingdom

env:
  countrycode: UK

on:
  workflow_dispatch:
  workflow_run:
    workflows: [start map builds]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maps:
          [
            {name: bermuda, url: https://download.geofabrik.de/europe/united-kingdom/bermuda-latest.osm.pbf, state: "0100"},
            {name: england, url: https://download.geofabrik.de/europe/united-kingdom/england-latest.osm.pbf, state: "0200"},
            {name: falklands, url: https://download.geofabrik.de/europe/united-kingdom/falklands-latest.osm.pbf, state: "0300"},
            {name: scotland, url: https://download.geofabrik.de/europe/united-kingdom/scotland-latest.osm.pbf, state: "0400"},
            {name: wales, url: https://download.geofabrik.de/europe/united-kingdom/wales-latest.osm.pbf, state: "0500"},
          ]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup Env
        run: |
          sudo apt-get update 
          sudo apt-get install wget openjdk-21-jre python3 pip
          pip install numpy
          echo "freeing ~10gb of disk space"
          sudo rm -rf /usr/local/lib/android || true

      - name: omsis-cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: osmosis
          key: osmosis-cache

      - name: omsis
        if: steps.cache.outputs.cache-hit != 'true'
        run: sh setup_env.sh

      - name: Download
        run: |
          wget ${{ matrix.maps.url }} -O tmp.pbf

      - name: Convert for filtering
        run: |
          ./osmosis/osmconvert tmp.pbf -o=tmp.o5m
          rm tmp.pbf

      - name: filter
        run: |
          ./osmosis/osmfilter tmp.o5m --keep="highway=* waterway=* landuse=* natural=* place=*" --out-o5m > tmp_filtered.o5m
          rm tmp.o5m

      - name: Convert for osmosis 
        run: |
          ./osmosis/osmconvert tmp_filtered.o5m -o=tmp_filtered.pbf
          rm tmp_filtered.o5m

      - name: Build mapsforge map
        run: |
          /usr/bin/time -v python generate_map.py -i tmp_filtered.pbf -c $countrycode -s ${{ matrix.maps.state }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-${{ matrix.maps.name }}
          path: ./*.map

