name: romania

env:
  countrycode: RO

on:
  workflow_dispatch:
  workflow_run:
    workflows: [start map builds]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maps:
          [
            {name: romania, url: https://download.geofabrik.de/europe/romania-latest.osm.pbf, state: "0000"},
          ]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup Env
        run: |
          sudo apt-get update 
          sudo apt-get install wget openjdk-21-jre python3 pip
          pip install numpy
          echo "freeing ~10gb of disk space"
          sudo rm -rf /usr/local/lib/android || true

      - name: omsis-cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: osmosis
          key: osmosis-cache

      - name: omsis
        if: steps.cache.outputs.cache-hit != 'true'
        run: sh setup_env.sh

      - name: Download
        run: |
          wget ${{ matrix.maps.url }} -O tmp.pbf

      - name: Convert for filtering
        run: |
          ./osmosis/osmconvert tmp.pbf -o=tmp.o5m
          rm tmp.pbf

      - name: filter
        run: |
          osmosis/osmfilter -v tmp.o5m \
          --keep="highway=primary =primary_link =secondary =secondary_link =tertiary =tertiary_link =trunk =trunk_link =cycleway =living_street =residential =road =track =unclassified" \
          --keep="highway=service and ( bicycle=designated or bicycle=yes or bicycle=permissive )" \
          --keep="highway=footway and ( bicycle=designated or bicycle=yes or bicycle=permissive )" \
          --keep="highway=path and ( bicycle=designated or bicycle=yes or bicycle=permissive )" \
          --keep="highway=pedestrian and ( bicycle=designated or bicycle=yes or bicycle=permissive )" \
          --keep="highway=unclassified and ( bicycle=designated or bicycle=yes or bicycle=permissive )" \
          --keep="waterway= landuse= natural=" \
          \
          --out-o5m > tmp1.o5m

          osmosis/osmfilter -v tmp1.o5m --modify-tags=" \
          highway=trunk_link to =primary \
          highway=trunk to =primary \
          highway=primary_link to =primary \
          highway=tertiary_link to =tertiary \
          highway=secondary_link to =secondary \
          highway=trunk_link to =trunk \
          highway=footway to =cycleway \
          highway=path to =cycleway \
          highway=pedestrian to =cycleway \
          highway=unclassified to =cycleway \
          " \
          --drop-author --drop-version --out-o5m > tmp_filtered.o5m

          rm tmp.o5m

      - name: Convert for osmosis 
        run: |
          ./osmosis/osmconvert tmp_filtered.o5m -o=tmp_filtered.pbf
          rm tmp_filtered.o5m

      - name: Build mapsforge map
        run: |
          /usr/bin/time -v python generate_map.py -i tmp_filtered.pbf -c $countrycode -s ${{ matrix.maps.state }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-${{ matrix.maps.name }}
          path: ./*.map

