name: Austria

on:
  workflow_run:
    workflows: [pre-requirements]
    types:
      - completed

jobs:
  build-austria:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup Env
        run: |
          sudo apt update 
          sudo apt install wget openjdk-21-jre 

      - name: omsis-cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: osmosis
          key: osmsis-cache

      - name: omsis
        if: steps.cache.outputs.cache-hit != 'true'
        run: sh setup_env_ci.sh

      - name: Build
        run: |
          wget https://download.geofabrik.de/europe/austria-latest.osm.pbf -O austria.pbf
          export datestring="$(printf '%(%y%m%d)T\n' -1)"
          export mapname=AT0000${datestring}3BR26204W02L
          echo "Creating map ${mapname}.map"
          sh generate_map_ci.sh -i austria.pbf -o ${mapname} 

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: austria
          path: ./*.map

