name: start map builds

on: 
  workflow_dispatch:
jobs:

  build-osmsis-cache:
    runs-on: ubuntu-latest

    steps:
      - name: checkJava
        run: |
          sudo apt-get update 
          sudo apt-get install wget openjdk-21-jre python3 pip
          java -XX:+PrintFlagsFinal -version
          free
          export _JAVA_OPTIONS="-Xmx12g"
          java -XX:+PrintFlagsFinal -version
